### ISSUE TITLE
buttons_and_dropdowns example does not run: "Cannot sent message when MessageBuilder doesn't have set either content, embed or files"

### ISSUE THREAD

**Issue by Four-Griffins** [nyxx-discord/nyxx_interactions#17]
I can't manage to make the ComponentMessageBuilder send anything. Whenever I run the buttons_and_dropdowns example, with a valid token of course, the interaction fails and the following error gets logged:
`[SHOUT] [Client] Got Error: Message: [Invalid argument(s): Cannot sent message when MessageBuilder doesn't have set either content, embed or files]. Stacktrace: 
Instance of '_StringStackTrace'`
The same happens every time I send or respond with a ComponentMessageBuilder instead of a normal MessageBuilder.

I haven't dug into the code much since I'm not very good at that, but it seems like the problem is that ComponentMessageBuilder doesn't set either content, embeds or files anywhere, and doesn't override canBeUsedAsNewMessage.

**Environment info**
 - OS: Artix Linux 5.15.10
 - Dart 2.16.0-134.0.dev
 - Nyxx version: both on 3.0.1 and 3.2.1, nyxx_interactions on 3.1.0

**Comment by abitofevrything** [comment]
You have to set the `content` just as you would with a `MessageBuilder`.
However, as you have noticed the example does not work. Maybe you can change this issue to reflect that?

**Comment by Four-Griffins** [comment]
I tried to do that, but I couldn't get that to work either. Do you need to use any of the `append` functions (`appendCode`, `appendEmbed` etc) for that? Because those only work if I'm not adding a `ComponentRow` like the example does. If I have both, I get a 400 invalid form body.
Here's the full error:
`[SHOUT] [Client] Got Error: Message: [[Code: 400] [Message: {"code": 50035, "errors": {"data": {"components": {"0": {"components": {"2": {"_errors": [{"code": "COMPONENT_LAYOUT_WIDTH_EXCEEDED", "message": "The specified component exceeds the maximum width"}]}}}}}}, "message": "Invalid Form Body"}]]`

**Comment by abitofevrything** [comment]
No, simply setting the `content` property should do. The issue you ran into after settings it is a seperate issue with the example.

**Comment by Four-Griffins** [comment]
Ah yes, I see now, I didn't read the error message well enough :sweat_smile:. Indeed, adding content worked fine. If I can figure out how to make pull request, I'll submit a fix for the example.
