### ISSUE TITLE
[Bug report] Guild commands not deleted if unregistered

### ISSUE THREAD

**Issue by abitofevrything** [nyxx-discord/nyxx_interactions#9]
## Describe the bug
Registering no guild command builders should result in all commands for that guild being deleted when `Interactions.sync()` is called. However, this is not the case and no guild commands are deleted for that guild.

This is also the case with `Interactions.syncOnReady()`.

## To reproduce
1. Register a command builder for a specific guild
2. Call `Interactions.sync()`
3. Stop the bot
4. Restart the bot, do not register the command builder and call `Interactions.sync()`
5. Command is still registered for that guild but should have been deleted

## Expected behaviour
After registering no commands for a specific guild, `Interactions.sync()` should delete all command for that guild.

## Desktop
- OS: Artix Linux 5.15.5-artix1-1
- Dart: 2.14.4
- nyxx_interactions: 2.9.0, appears to also be present in 3.0.0-dev-0 but have not tested.

## Additional context
[This for loop](https://github.com/nyxx-discord/nyxx_interactions/blob/75eada35047ef03af3e2412b2b82b55136df2c3c/lib/src/Interactions.dart#L128-L136) will not call `bulkOverrideGuildCommands()` for any guilds with no commands registered as they will not be a partition. This means that commands for any guild will be left untouched if no command builders are registered for it, causing the issue.

**Comment by l7ssha** [comment]
I check out the problem and current implementation does not allow for easy fix to this problem.
Possible solutions are:
 - rewriting internal registering of commands
 - adding alternative way of removing guild commands 

Right now I can't see to fix this bug via hotfix. It probably will be fixed and released with `3.0.0`

**Comment by abitofevrything** [comment]
The best way I could think of was pulling the guild commands for each guild the bot is in and syncing based on that... But it's slow and somewhat inefficient.

**Comment by l7ssha** [comment]
Yeah that would be bad also because of rate limits. Rate limit bucked for these endpoint is application id so for bigger number of guild that solution isnt viable. I like idea of adding additional method to `IInteractions` like `removeCommands(List<Snowflake> guilds)` which will remove (override with []) commands for provided guilds

**Comment by abitofevrything** [comment]
That would then be inconsistent with global commands which are unregistered of you register no global commands... Plus you'd have to remember to remove them.

There isn't really an ideal solution unless discord adds a way to batch fetch guild commands.

**Comment by l7ssha** [comment]
Yeah, but library doesnt have to track guilds in case of global commands. With guilds there is no easy way of implementing this, but I think my proposal is most efficient approach to this problem.
